#!/bin/zsh
PRODUCTION_HOSTNAME=markets.bisq.network
DEVELOPMENT_HOSTNAME=bisq-markets.appspot.com

for query in `cat tests`;do
    curl -i -n -s \
        -w "%{url_effective} %{http_code} %{time_total}\n" \
        -o /dev/null \
        "https://${DEVELOPMENT_HOSTNAME}${query}" &
done
